apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  volumes:
  - name: p-db
    persistentVolumeClaim:
      claimName: p-db
  containers:
  - name: p-db
    image: docker.io/postgres:14.2
    imagePullPolicy: Always
    volumeMounts:
    - name: p-db
      mountPath: /var/lib/postgresql
    livenessProbe:
      httpGet:
        path: /polls/
        port: 8000
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
        ephemeral-storage: 10Mi
    ports:
    - containerPort: 8000
    env:
    - name: DB_ENGINE
      value: "postgres"
    - name: DJANGO_ADMIN_EMAIL
      value: "test@test.test"
    - name: DJANGO_ADMIN_USERNAME
      value: "test"
    - name: DJANGO_SUPERUSER_PASSWORD
      value: "test"
    - name: POSTGRES_DB
      value: mysitedb
    - name: POSTGRES_USER
      value: mysiteuser
    - name: POSTGRES_PASSWORD
      value: mysitepassword